// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrHKMQuqTVauI2yLA6_fsQLUFMcDIbl1s',
    appId: '1:803543089420:web:c95fec0fef6d6e1af1c929',
    messagingSenderId: '803543089420',
    projectId: 'slugarbage',
    authDomain: 'slugarbage.firebaseapp.com',
    storageBucket: 'slugarbage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9IOZnQnnSd7LC6YDeWkhxR-8XYufEYNU',
    appId: '1:803543089420:android:487d4bbac8d25566f1c929',
    messagingSenderId: '803543089420',
    projectId: 'slugarbage',
    storageBucket: 'slugarbage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgwJ38N4CNlLy9F9C2wQOegZx1ovGk6ec',
    appId: '1:803543089420:ios:c6e0a92eb24e892af1c929',
    messagingSenderId: '803543089420',
    projectId: 'slugarbage',
    storageBucket: 'slugarbage.appspot.com',
    iosBundleId: 'com.example.slugarbage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgwJ38N4CNlLy9F9C2wQOegZx1ovGk6ec',
    appId: '1:803543089420:ios:8128fd108b9ccde4f1c929',
    messagingSenderId: '803543089420',
    projectId: 'slugarbage',
    storageBucket: 'slugarbage.appspot.com',
    iosBundleId: 'com.example.slugarbage.RunnerTests',
  );
}
